language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1

notifications:
    email: false

env:
    - TESTER_PHP_BIN="php"

matrix:
    include:
        - php: 7.1
          env: TESTER_PHP_BIN=phpdbg
    allow_failures:
        - php: 7.1
          env: TESTER_PHP_BIN=phpdbg

before_install:
    - composer self-update
    - phpenv config-rm xdebug.ini || true

install:
    - composer install -a --prefer-dist --no-progress --no-suggest --no-interaction

script:
   - ./vendor/bin/parallel-lint EventCalendar tests -e php,phpt
   - ./vendor/bin/phpstan analyze -l 6 -c phpstan.neon EventCalendar tests
    - if [ "$TESTER_PHP_BIN" == "php" ]; then ./vendor/bin/run-tests -p php tests -s; fi
    - if [ "$TESTER_PHP_BIN" == "phpdbg" ]; then ./vendor/bin/run-tests -p phpdbg tests -s --coverage coverage.xml --coverage-src EventCalendar; fi

after_failure:
    - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
